#!/bin/sh
##############################################################################
# LOCAL DEVELOPMENT BOOTSTRAP ONLY
#
# This script generates runtime secrets and configuration for local
# development. It is NOT the production secret management path.
# Production deployments must use a proper secret management system.
#
# Generated artifacts are stored in a Docker named volume and persist
# across restarts. Delete the bootstrap_data volume to regenerate.
##############################################################################

set -e

BOOTSTRAP_DIR="/bootstrap"

if [ -f "$BOOTSTRAP_DIR/.initialized" ]; then
    echo "[dev-bootstrap] Already initialized, skipping."
    exit 0
fi

echo "[dev-bootstrap] Generating local development runtime values..."

# Generate random credentials and keys
DB_ROOT_PASS=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 32)
DB_APP_PASS=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 32)
DB_NAME="siteops_$(head -c 4 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 8)"
DB_USER="app_$(head -c 4 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 8)"
APP_KEY=$(head -c 48 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 64)
TAX_ID_KEY=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 64)
CSRF_SECRET=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 48)
SEED_ADMIN_PASS=$(head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 24)

# Write individual secret files
printf '%s' "$DB_ROOT_PASS" > "$BOOTSTRAP_DIR/db_root_password"
printf '%s' "$DB_APP_PASS" > "$BOOTSTRAP_DIR/db_app_password"
printf '%s' "$DB_NAME" > "$BOOTSTRAP_DIR/db_name"
printf '%s' "$DB_USER" > "$BOOTSTRAP_DIR/db_user"
printf '%s' "$APP_KEY" > "$BOOTSTRAP_DIR/app_key"
printf '%s' "$TAX_ID_KEY" > "$BOOTSTRAP_DIR/tax_id_key"
printf '%s' "$CSRF_SECRET" > "$BOOTSTRAP_DIR/csrf_secret"
printf '%s' "$SEED_ADMIN_PASS" > "$BOOTSTRAP_DIR/seed_admin_password"

# Write PHP config that the application reads at runtime
cat > "$BOOTSTRAP_DIR/app_config.php" << PHPEOF
<?php
/**
 * AUTO-GENERATED by dev-bootstrap.sh — DO NOT COMMIT
 * Local development configuration only.
 */
return [
    'db_host'               => '127.0.0.1',
    'db_port'               => 3307,
    'db_database'           => '${DB_NAME}',
    'db_username'           => '${DB_USER}',
    'db_password'           => '${DB_APP_PASS}',
    'app_key'               => '${APP_KEY}',
    'tax_id_encryption_key' => '${TAX_ID_KEY}',
    'csrf_secret'           => '${CSRF_SECRET}',
    'seed_admin_password'   => '${SEED_ADMIN_PASS}',
];
PHPEOF

touch "$BOOTSTRAP_DIR/.initialized"
echo "[dev-bootstrap] Bootstrap complete."
echo "[dev-bootstrap] Dev admin: username=admin password=$SEED_ADMIN_PASS"
